from enum import StrEnum


class ErrorCode(StrEnum):
    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BAD_REQUEST = "BAD_REQUEST"

    # Authentication
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_USER_ALREADY_EXISTS = "AUTH_USER_ALREADY_EXISTS"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"

    # Authorization
    FORBIDDEN = "FORBIDDEN"

    # Database
    DB_ERROR = "DB_ERROR"
    DB_INTEGRITY_ERROR = "DB_INTEGRITY_ERROR"
    DB_UNAVAILABLE = "DB_UNAVAILABLE"

    # External services
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    EXTERNAL_SERVICE_UNAVAILABLE = "EXTERNAL_SERVICE_UNAVAILABLE"
    EXTERNAL_SERVICE_TIMEOUT = "EXTERNAL_SERVICE_TIMEOUT"
    EXTERNAL_SERVICE_RATE_LIMITED = "EXTERNAL_SERVICE_RATE_LIMITED"