from collections.abc import Sequence

revision: str = "05f8bec9c5cc"
down_revision: str | Sequence[str] | None = "b61c0b5e02e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
