"""doc processing

Revision ID: 638d77373779
Revises: e16253370088
Create Date: 2026-10-02 12:12:03.227189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638d77373779'
down_revision: Union[str, Sequence[str], None] = 'e16253370088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
